org.gradle.jvmargs=-Xmx1500m -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=192m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
