import 'package:flutter/widgets.dart';

class AppStrings {
  const AppStrings(this.locale);
  final Locale locale;

  static const _ar = <String, String>{
    'appName': 'نظام المبيعات والمشتريات والإدارة المتكاملة',
    'shortName': 'النظام المتكامل',
    'company': 'محمد الحاج سوفت',
    'login': 'تسجيل الدخول',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'logout': 'تسجيل الخروج',
    'setup': 'إعداد المؤسسة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'add': 'إضافة',
    'search': 'بحث',
    'dashboard': 'لوحة التحكم',
    'sales': 'المبيعات ونقطة البيع',
    'salesReturns': 'مرتجعات المبيعات',
    'purchases': 'المشتريات',
    'purchaseReturns': 'مرتجعات المشتريات',
    'inventory': 'الأصناف والمخزون',
    'referenceData': 'البيانات المرجعية',
    'stockTransfers': 'تحويلات المخزون',
    'stockCount': 'الجرد والتسويات',
    'expensesIncome': 'المصروفات والإيرادات',
    'users': 'المستخدمون والصلاحيات',
    'customers': 'العملاء',
    'suppliers': 'الموردون',
    'cash': 'الصناديق والسندات',
    'accounting': 'الحسابات والقيود',
    'reports': 'التقارير',
    'settings': 'الإعدادات',
    'product': 'صنف',
    'products': 'الأصناف',
    'newProduct': 'إضافة صنف',
    'newCustomer': 'إضافة عميل',
    'newSupplier': 'إضافة مورد',
    'nameArabic': 'الاسم العربي',
    'sku': 'رمز الصنف SKU',
    'barcode': 'الباركود',
    'price': 'السعر',
    'quantity': 'الكمية',
    'total': 'الإجمالي',
    'paid': 'المدفوع',
    'due': 'المتبقي',
    'postSale': 'ترحيل البيع',
    'postPurchase': 'ترحيل الشراء',
    'empty': 'لا توجد بيانات للعرض',
    'error': 'حدث خطأ',
    'success': 'تم الحفظ بنجاح',
    'organizationName': 'اسم المؤسسة',
    'branchName': 'اسم الفرع',
    'warehouseName': 'اسم المخزن',
    'cashboxName': 'اسم الصندوق',
    'adminName': 'اسم المدير',
    'confirm': 'تأكيد',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'English',
    'todaySales': 'مبيعات اليوم',
    'todayPurchases': 'مشتريات اليوم',
    'expenses': 'المصروفات',
    'cashBalance': 'الرصيد النقدي',
    'customerDebt': 'ديون العملاء',
    'supplierDue': 'مستحقات الموردين',
    'lowStock': 'أصناف منخفضة',
    'newReceipt': 'سند قبض',
    'newVoucher': 'سند صرف',
    'cashTransfer': 'تحويل نقدي',
    'manualJournal': 'قيد يدوي',
    'about': 'حول التطبيق',
    'theme': 'المظهر',
    'backup': 'النسخ الاحتياطي',
    'license': 'الترخيص',
    'unit': 'الوحدة',
    'warehouse': 'المخزن',
    'cashbox': 'الصندوق',
    'customer': 'العميل',
    'supplier': 'المورد',
    'amount': 'المبلغ',
    'date': 'التاريخ',
    'notes': 'ملاحظات',
    'required': 'هذا الحقل مطلوب',
    'invalidAmount': 'أدخل مبلغاً صحيحاً أكبر من صفر',
    'demo': 'تحميل بيانات عرض اختيارية',
  };

  static const _en = <String, String>{
    'appName': 'Integrated Sales, Purchases & Management System',
    'shortName': 'Integrated System',
    'company': 'Mohammed Al-Haj Soft',
    'login': 'Sign in',
    'username': 'Username',
    'password': 'Password',
    'logout': 'Sign out',
    'setup': 'Organization setup',
    'save': 'Save',
    'cancel': 'Cancel',
    'add': 'Add',
    'search': 'Search',
    'dashboard': 'Dashboard',
    'sales': 'Sales & POS',
    'salesReturns': 'Sales Returns',
    'purchases': 'Purchases',
    'purchaseReturns': 'Purchase Returns',
    'inventory': 'Products & Inventory',
    'referenceData': 'Reference data',
    'stockTransfers': 'Stock Transfers',
    'stockCount': 'Stock Count & Adjustments',
    'expensesIncome': 'Expenses & Income',
    'users': 'Users & Permissions',
    'customers': 'Customers',
    'suppliers': 'Suppliers',
    'cash': 'Cashboxes & Vouchers',
    'accounting': 'Accounting & Journals',
    'reports': 'Reports',
    'settings': 'Settings',
    'product': 'Product',
    'products': 'Products',
    'newProduct': 'Add product',
    'newCustomer': 'Add customer',
    'newSupplier': 'Add supplier',
    'nameArabic': 'Arabic name',
    'sku': 'SKU',
    'barcode': 'Barcode',
    'price': 'Price',
    'quantity': 'Quantity',
    'total': 'Total',
    'paid': 'Paid',
    'due': 'Due',
    'postSale': 'Post sale',
    'postPurchase': 'Post purchase',
    'empty': 'No data to display',
    'error': 'An error occurred',
    'success': 'Saved successfully',
    'organizationName': 'Organization name',
    'branchName': 'Branch name',
    'warehouseName': 'Warehouse name',
    'cashboxName': 'Cashbox name',
    'adminName': 'Administrator name',
    'confirm': 'Confirm',
    'language': 'Language',
    'arabic': 'العربية',
    'english': 'English',
    'todaySales': 'Today sales',
    'todayPurchases': 'Today purchases',
    'expenses': 'Expenses',
    'cashBalance': 'Cash balance',
    'customerDebt': 'Customer debt',
    'supplierDue': 'Supplier dues',
    'lowStock': 'Low stock products',
    'newReceipt': 'Receipt voucher',
    'newVoucher': 'Payment voucher',
    'cashTransfer': 'Cash transfer',
    'manualJournal': 'Manual journal',
    'about': 'About',
    'theme': 'Theme',
    'backup': 'Backup',
    'license': 'License',
    'unit': 'Unit',
    'warehouse': 'Warehouse',
    'cashbox': 'Cashbox',
    'customer': 'Customer',
    'supplier': 'Supplier',
    'amount': 'Amount',
    'date': 'Date',
    'notes': 'Notes',
    'required': 'This field is required',
    'invalidAmount': 'Enter a valid positive amount',
    'demo': 'Load optional demo data',
  };

  String get(String key) =>
      (locale.languageCode == 'ar' ? _ar : _en)[key] ?? key;
}

extension TranslationContext on BuildContext {
  String tr(String key) => AppStrings(Localizations.localeOf(this)).get(key);
}
